# letsGetTogether Codelab

use_frameworks!
platform :ios, '10.0'

pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/RemoteConfig'

target 'letsGetTogether' do
end
